name: Deploy Frontend to Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag образа для PROD (обычно latest или SHA коммита)'
        required: false
        default: 'latest'

jobs:
  deploy-prod:
    runs-on: [self-hosted, spothub-1]

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Никакого sync-env — манифесты уже лежат в кластере как нужно

      - name: Deploy frontend to PROD namespace
        run: |
          TAG="${IMAGE_TAG:-latest}"
          IMAGE="${DOCKERHUB_USERNAME}/full-mvp-frontend:${TAG}"
          echo "Deploying image to PROD: $IMAGE"
          # имя контейнера внутри deployment мы уже проверяли: frontend
          kubectl set image deployment/sporthub-frontend frontend=$IMAGE -n sporthub-prod
          kubectl rollout status deployment/sporthub-frontend -n sporthub-prod

      - name: Smoke test frontend in PROD
        run: |
          # Просто проверим, что по сервису frontend отдается главная страница
          kubectl run frontend-smoke-prod --rm -i --restart=Never \
            --image=curlimages/curl -n sporthub-prod -- \
            curl -fsS http://sporthub-frontend
